/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.damage.frames;

import com.damage.grafos.Grafo;
import com.damage.grafos.No;
import com.damage.grafos.armazenamento.MatrizIncidencia;
import com.damage.grafos.estruturasdedados.GeraPosicoesRamdomicas;
import com.damage.modeloTabelaGrafos.ModeloTabelaAresta;
import com.damage.modeloTabelaGrafos.ModeloTabelaGrafos;
import com.damage.modeloTabelaGrafos.ModeloTabelaNo;
import javax.swing.JOptionPane;

/**
 *
 * @author David .V
 */
public class FrameCriarGrafoEditor extends javax.swing.JFrame {

    private Grafo grafo = new Grafo();
    private ModeloTabelaGrafos grafos;
    
    public FrameCriarGrafoEditor() {
        initComponents();
    }
    
    public FrameCriarGrafoEditor(ModeloTabelaGrafos grafos) {
        this.grafos = grafos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaNos = new javax.swing.JTable();
        botaoCriarNo = new javax.swing.JButton();
        botaoEditarNo = new javax.swing.JButton();
        botaoExcluirNo = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        textoNome = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaArestas = new javax.swing.JTable();
        botaoCriarAresta = new javax.swing.JButton();
        botaoEditarAresta = new javax.swing.JButton();
        botaoExcluirAresta = new javax.swing.JButton();
        botaoCriarGrafo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nós"));

        tabelaNos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        this.tabelaNos.setModel(new ModeloTabelaNo(grafo.getNo()));
        this.tabelaNos.getColumnModel().getColumn(0).setHeaderValue("Id");

        jScrollPane1.setViewportView(tabelaNos);

        botaoCriarNo.setText("Criar");
        botaoCriarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarNoActionPerformed(evt);
            }
        });

        botaoEditarNo.setText("Editar");
        botaoEditarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarNoActionPerformed(evt);
            }
        });

        botaoExcluirNo.setText("Excluir");
        botaoExcluirNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCriarNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoEditarNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoExcluirNo)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botaoCriarNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEditarNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluirNo)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        labelNome.setText("Nome");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Arestas"));

        tabelaArestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "No", "No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        this.tabelaArestas.setModel(new ModeloTabelaAresta(grafo.getAresta()));
        this.tabelaArestas.getColumnModel().getColumn(0).setHeaderValue("Id");
        this.tabelaArestas.getColumnModel().getColumn(1).setHeaderValue("Nó");
        this.tabelaArestas.getColumnModel().getColumn(2).setHeaderValue("Nó");

        jScrollPane2.setViewportView(tabelaArestas);

        botaoCriarAresta.setText("Criar");
        botaoCriarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarArestaActionPerformed(evt);
            }
        });

        botaoEditarAresta.setText("Editar");
        botaoEditarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarArestaActionPerformed(evt);
            }
        });

        botaoExcluirAresta.setText("Excluir");
        botaoExcluirAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirArestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCriarAresta)
                    .addComponent(botaoEditarAresta)
                    .addComponent(botaoExcluirAresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoCriarAresta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoEditarAresta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoExcluirAresta)))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        botaoCriarGrafo.setText("Criar Grafo");
        botaoCriarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCriarGrafo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(botaoCriarGrafo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCriarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarGrafoActionPerformed
        if(this.textoNome.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Insira um nome de no minimo 1 caractere para o grafo", "Insira um nome", 1);
        }else if(this.grafo.getNo().size() < 1){
            JOptionPane.showMessageDialog(null, "Crie pelo menos um nó para o grafo", "Crie um nó", 1);
        }
        else{
            grafo.update();
            grafo.setNome(this.textoNome.getText());
            grafos.getGrafos().add(grafo);
            grafos.fireTableDataChanged();
            JOptionPane.showMessageDialog(null, "Grafo criado comsucesso", "Sucesso", 1);
            this.dispose();
            GeraPosicoesRamdomicas gerador = new GeraPosicoesRamdomicas();
            for(int i =0; i<grafo.getNo().size(); i++)
             {
                 int x = gerador.getNumeroRamdomX(),y = gerador.getNumeroRamdomY();
                   for(int j =0; j<grafo.getNo().size(); j++)
                   {
                       if(x>grafo.getNo().getNo(j).getCordenadaX()-50&&x<grafo.getNo().getNo(j).getCordenadaX()+50&&y>grafo.getNo().getNo(j).getCordenadaY()-50&&y<grafo.getNo().getNo(j).getCordenadaY()+50)
                          i--;
                   }
                 grafo.getNo().getNo(i).setCordenadaX(x);
                 grafo.getNo().getNo(i).setCordenadaY(y);

             }
        }
    }//GEN-LAST:event_botaoCriarGrafoActionPerformed

    private void botaoCriarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarNoActionPerformed
        FrameCriarNo.abrir((ModeloTabelaNo) tabelaNos.getModel());
    }//GEN-LAST:event_botaoCriarNoActionPerformed

    private void botaoCriarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarArestaActionPerformed
        if(this.tabelaNos.getModel().getRowCount() < 1){
            JOptionPane.showMessageDialog(null, "Crie pelo menos um nó para criar arestas", "Crie um nó", 1);
        }
        else{
            FrameCriarAresta.abrir((ModeloTabelaAresta)this.tabelaArestas.getModel(),(ModeloTabelaNo) this.tabelaNos.getModel());
        }
        
    }//GEN-LAST:event_botaoCriarArestaActionPerformed

    private void botaoExcluirNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirNoActionPerformed
        ModeloTabelaNo modeloNo = (ModeloTabelaNo) this.tabelaNos.getModel();
        ModeloTabelaAresta modeloAresta = (ModeloTabelaAresta) this.tabelaArestas.getModel();
        if(this.tabelaNos.getSelectedRow() == -1){
             JOptionPane.showMessageDialog(null, "Selecione um nó para realizar a Exclusão", "Selecione o nó", 1);
            return;
        }
        
        if(modeloAresta.getArestas().possuiAresta(this.grafo.getNo().getNo(this.tabelaNos.getSelectedRow()))){
            JOptionPane.showMessageDialog(null, "O nó selecionado está sendo utilizado em arestas\nRealize a exclusão da aresta para prosseguir", "Exclua a aresta", 1);
            return;
        }
        
        this.grafo.getNo().remove(this.tabelaNos.getSelectedRow());
        this.grafos.fireTableDataChanged();
        modeloNo.fireTableDataChanged();
    }//GEN-LAST:event_botaoExcluirNoActionPerformed

    private void botaoExcluirArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirArestaActionPerformed
        ModeloTabelaAresta modeloAresta = (ModeloTabelaAresta) this.tabelaArestas.getModel();
        if(this.tabelaArestas.getSelectedRow() == -1){
             JOptionPane.showMessageDialog(null, "Selecione uma aresta para realizar a Exclusão", "Selecione a Aresta", 1);
            return;
        }
        this.grafo.getAresta().remove(this.tabelaArestas.getSelectedRow());
        modeloAresta.fireTableDataChanged();
    }//GEN-LAST:event_botaoExcluirArestaActionPerformed

    private void botaoEditarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarNoActionPerformed
        ModeloTabelaNo modeloNo = (ModeloTabelaNo) this.tabelaNos.getModel();
        ModeloTabelaAresta modeloAresta = (ModeloTabelaAresta) this.tabelaArestas.getModel();
        if(this.tabelaNos.getSelectedRow() == -1){
             JOptionPane.showMessageDialog(null, "Selecione um no para realizar a edição", "Selecione um nó", 1);
            return;
        }
        FrameEditarNo.abrir(modeloNo, modeloAresta ,modeloNo.getNos().getNo(tabelaNos.getSelectedRow()));
    }//GEN-LAST:event_botaoEditarNoActionPerformed

    private void botaoEditarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarArestaActionPerformed
        ModeloTabelaAresta modeloAresta = (ModeloTabelaAresta) this.tabelaArestas.getModel();
        ModeloTabelaNo modeloNo = (ModeloTabelaNo) this.tabelaNos.getModel();
        if(this.tabelaArestas.getSelectedRow() == -1){
             JOptionPane.showMessageDialog(null, "Selecione uma aresta para realizar a edição", "Selecione um aresta", 1);
            return;
        }
        FrameEditarAresta.abrir(modeloAresta, modeloAresta.getArestas().getAresta(tabelaArestas.getSelectedRow()) ,modeloNo);
    }//GEN-LAST:event_botaoEditarArestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCriarGrafoEditor().setVisible(true);
            }
        });
    }
    
    public static void abrir(ModeloTabelaGrafos grafos){
        new FrameCriarGrafoEditor(grafos).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarAresta;
    private javax.swing.JButton botaoCriarGrafo;
    private javax.swing.JButton botaoCriarNo;
    private javax.swing.JButton botaoEditarAresta;
    private javax.swing.JButton botaoEditarNo;
    private javax.swing.JButton botaoExcluirAresta;
    private javax.swing.JButton botaoExcluirNo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTable tabelaArestas;
    private javax.swing.JTable tabelaNos;
    private javax.swing.JTextField textoNome;
    // End of variables declaration//GEN-END:variables

    public ModeloTabelaGrafos getGrafos() {
        return grafos;
    }

    public void setGrafos(ModeloTabelaGrafos grafos) {
        this.grafos = grafos;
    }

}
