
package com.damage.frames;

import com.damage.grafos.Grafo;
import com.damage.grafos.armazenamento.UtilCaminho;
import com.damage.modeloTabelaGrafos.ModeloTabelaArestaPeso;
import javax.swing.JOptionPane;


public class FrameMenorCaminho extends javax.swing.JFrame {

    /**
     * Creates new form FrameMenorCaminho
     */
    Grafo grafo;
    public FrameMenorCaminho() {
        initComponents();
    }
    
    public FrameMenorCaminho(Grafo grafo) {
        this.grafo = grafo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaArestas = new javax.swing.JTable();
        botaoModificarPeso = new javax.swing.JButton();
        botaoMenorCaminho = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaArestas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Aresta", "Peso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        this.tabelaArestas.setModel(new ModeloTabelaArestaPeso(grafo.getAresta()));
        jScrollPane1.setViewportView(tabelaArestas);

        botaoModificarPeso.setText("Modificar Peso");
        botaoModificarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModificarPesoActionPerformed(evt);
            }
        });

        botaoMenorCaminho.setText("Calcular Ciclos");
        botaoMenorCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenorCaminhoActionPerformed(evt);
            }
        });

        resultados.setColumns(20);
        resultados.setRows(5);
        jScrollPane2.setViewportView(resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoMenorCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(botaoModificarPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoModificarPeso)
                    .addComponent(botaoMenorCaminho))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoModificarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModificarPesoActionPerformed
       if(this.tabelaArestas.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione um nó para modificar o peso");
            return;
        }
        int peso = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Informe o novo peso da aresta", "Informe o novo peso da aresta", 1));
        if(peso < 0){
            JOptionPane.showMessageDialog(null, "O peso não pode ser menor que 0");
            return;
        }
        grafo.getAresta().getAresta(this.tabelaArestas.getSelectedRow()).setPeso(peso);
        ModeloTabelaArestaPeso tabela = (ModeloTabelaArestaPeso)tabelaArestas.getModel();
        tabela.fireTableDataChanged();
    }//GEN-LAST:event_botaoModificarPesoActionPerformed

    private void botaoMenorCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenorCaminhoActionPerformed
        this.resultados.setText(new UtilCaminho().calcularCiclosToString(grafo));
    }//GEN-LAST:event_botaoMenorCaminhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMenorCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMenorCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMenorCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMenorCaminho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMenorCaminho().setVisible(true);
            }
        });
    }
    
    public static void abrir(Grafo grafo){
        new FrameMenorCaminho(grafo).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMenorCaminho;
    private javax.swing.JButton botaoModificarPeso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea resultados;
    private javax.swing.JTable tabelaArestas;
    // End of variables declaration//GEN-END:variables
}
