
package com.damage.frames;

import com.damage.grafos.Aresta;
import com.damage.grafos.No;
import com.damage.grafos.estruturasdedados.VectorAresta;
import com.damage.grafos.estruturasdedados.VectorNo;
import com.damage.modeloTabelaGrafos.ComboBoxNo;
import com.damage.modeloTabelaGrafos.ModeloTabelaAresta;
import com.damage.modeloTabelaGrafos.ModeloTabelaNo;
import javax.swing.JOptionPane;


public class FrameCriarAresta extends javax.swing.JFrame {

    Aresta aresta = new Aresta();
    ModeloTabelaAresta arestas;
    ModeloTabelaNo nos;
    
    public FrameCriarAresta() {
        initComponents();
    }
    
    public FrameCriarAresta(ModeloTabelaAresta arestas, ModeloTabelaNo nos) {
        this.arestas = arestas;
        this.nos = nos;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboBoxNo1 = new javax.swing.JComboBox<>();
        comboBoxNo2 = new javax.swing.JComboBox<>();
        labelNo1 = new javax.swing.JLabel();
        labelNo2 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        textoNomeAresta = new javax.swing.JTextField();
        botaoCriarAresta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informe os dados da Aresta"));

        comboBoxNo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        this.comboBoxNo1.setModel(new ComboBoxNo((VectorNo<No>) nos.getNos()));

        comboBoxNo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        this.comboBoxNo2.setModel(new ComboBoxNo((VectorNo<No>) nos.getNos()));

        labelNo1.setText("Nó");

        labelNo2.setText("Nó");

        labelNome.setText("Nome:");

        botaoCriarAresta.setText("Criar");
        botaoCriarAresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarArestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNomeAresta))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNo2)
                            .addComponent(comboBoxNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(botaoCriarAresta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textoNomeAresta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNo2)
                    .addComponent(labelNo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoCriarAresta)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCriarArestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarArestaActionPerformed
        ComboBoxNo combobox;
        if(this.textoNomeAresta.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Insira um nome de no minimo 1 caractere para o Nó", "Insira um nome", 1);
        }else if(this.arestas.getArestas().findIndexById(this.textoNomeAresta.getText()) != -1){
                        JOptionPane.showMessageDialog(null, "Já existe uma aresta com o nome informado", "Aresta já criada", 1);
        }
        else if(this.comboBoxNo1.getSelectedItem() == null || this.comboBoxNo2.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Selecione os nós da aresta", "Selecione os Nós", 1);
        }
        else{
            combobox = (ComboBoxNo) this.comboBoxNo1.getModel();
            this.aresta.setNo1(combobox.getSelectedNo());
            combobox = (ComboBoxNo) this.comboBoxNo2.getModel();
            this.aresta.setNo2(combobox.getSelectedNo());
            this.aresta.setId(this.textoNomeAresta.getText());
            this.aresta.setIndex(this.arestas.getArestas().size());
            this.arestas.getArestas().add(aresta);
            this.arestas.fireTableDataChanged();
            this.dispose();
        }
    }//GEN-LAST:event_botaoCriarArestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCriarAresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCriarAresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCriarAresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCriarAresta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCriarAresta().setVisible(true);
            }
        });
    }
    
    public static void abrir(ModeloTabelaAresta arestas, ModeloTabelaNo nos){
        new FrameCriarAresta(arestas,nos).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarAresta;
    private javax.swing.JComboBox<String> comboBoxNo1;
    private javax.swing.JComboBox<String> comboBoxNo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNo1;
    private javax.swing.JLabel labelNo2;
    private javax.swing.JLabel labelNome;
    private javax.swing.JTextField textoNomeAresta;
    // End of variables declaration//GEN-END:variables
}
