package com.damage.frames;


import com.damage.Response.Response;
import com.damage.grafos.Grafo;
import com.damage.grafos.armazenamento.DefinicaoFormal;
import com.damage.grafos.armazenamento.MatrizIncidencia;
import com.damage.modeloTabelaGrafos.ModeloTabelaGrafos;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David .V
 */
public class FrameCriarGrafoDefinicaoFormal extends javax.swing.JFrame {

    private ModeloTabelaGrafos grafos;
    Grafo grafo;
    
    public FrameCriarGrafoDefinicaoFormal(ModeloTabelaGrafos grafos) {
        this.grafos = grafos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        botaoCriarGrafo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDefinicaoFormal = new javax.swing.JTextArea();
        mensagem = new javax.swing.JLabel();
        botaoModelo = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        textoNomeGrafo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Definição Formal"));

        botaoCriarGrafo.setText("Criar Grafo");
        botaoCriarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCriarGrafoActionPerformed(evt);
            }
        });

        textoDefinicaoFormal.setColumns(20);
        textoDefinicaoFormal.setRows(5);
        textoDefinicaoFormal.setText("G=({a,b,c},{1,2,3,4},{g(1)=(a-b),g(2)=(b-c),g(3)=(a-c),g(4)=(c-b)})");
        jScrollPane1.setViewportView(textoDefinicaoFormal);

        mensagem.setForeground(new java.awt.Color(255, 0, 0));
        mensagem.setText("-");
        mensagem.setMaximumSize(new java.awt.Dimension(30, 14));

        botaoModelo.setText("Redefinir Modelo");
        botaoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModeloActionPerformed(evt);
            }
        });

        labelNome.setText("Nome:");

        textoNomeGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNomeGrafoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(botaoCriarGrafo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoModelo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriarGrafo)
                    .addComponent(botaoModelo)
                    .addComponent(labelNome)
                    .addComponent(textoNomeGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCriarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCriarGrafoActionPerformed
        if(this.textoNomeGrafo.getText().length() < 4 ){
            JOptionPane.showMessageDialog(null, "Insira um nome de no minio 4 caracteres para o grafo", "Insira um nome", 1);
        }else{
            grafo = new Grafo();
            grafo.setNome(this.textoNomeGrafo.getText());
            Response response = DefinicaoFormal.build(this.textoDefinicaoFormal.getText(), grafo);
            MatrizIncidencia.buildMatrizIncidenciaGrafo(grafo);
            if(response.getCode() == 400){
                JOptionPane.showMessageDialog(null, response.getMessage(), "Erro ao ler definição formal", 1);
            }
            else{
                grafos.getGrafos().add(grafo);
                JOptionPane.showMessageDialog(null, "Grafo criado com sucesso", "Sucesso", 1);
                grafos.fireTableDataChanged();
                this.dispose();
            }
        }
    }//GEN-LAST:event_botaoCriarGrafoActionPerformed

    private void botaoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModeloActionPerformed
        this.textoDefinicaoFormal.setText("G=({a,b},{1},{g(1)=(a,b)})");
    }//GEN-LAST:event_botaoModeloActionPerformed

    private void textoNomeGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNomeGrafoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNomeGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(ModeloTabelaGrafos grafos) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoDefinicaoFormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoDefinicaoFormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoDefinicaoFormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCriarGrafoDefinicaoFormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameCriarGrafoDefinicaoFormal(grafos).setVisible(true);
            }
        });
    }
    
    public static void abrir(ModeloTabelaGrafos grafos) {
        new FrameCriarGrafoDefinicaoFormal(grafos).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCriarGrafo;
    private javax.swing.JButton botaoModelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel mensagem;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextArea textoDefinicaoFormal;
    private javax.swing.JTextField textoNomeGrafo;
    // End of variables declaration//GEN-END:variables
}
